apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  type: LoadBalancer
  loadBalancerIP: 35.204.234.135
  externalTrafficPolicy: Local
  selector:
    app: vault
  ports:
    - name: vault-port
      port: 443
      targetPort: 8200
      protocol: TCP
